/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import DAO.MarcaDAO;
import Entidad.Marca;
import java.util.List;
import DAO.ConcesionarioDAO;
import Entidad.Concesionario;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public final class FrmConcesionarioMarca extends javax.swing.JFrame {

    //Creo un nuevo objeto/instancia de tipo ConcesionarioDAO
    ConcesionarioDAO conceDAO = new ConcesionarioDAO();
    //Creo un nuevo objeto/instancia de tipo Concesionario
    Concesionario conce = new Concesionario();
    //Creo un nuevo objeto/instancia de tipo MarcaDAO
    MarcaDAO marcaDAO = new MarcaDAO();
    //Creo un nuevo objeto/instancia de tipo Marca
    Marca marca = new Marca();

    /**
     * Creates new form FrmConcesionarioMarca
     *
     * @throws java.sql.SQLException
     */
    public FrmConcesionarioMarca() throws SQLException {
        initComponents();
        comboBoxConcesionario();
        comboBoxMarca();
        mostrarTablaMarcas(((Concesionario) comboConcesionario.getSelectedItem()).getIdConcesionario());
    }

    private void comboBoxConcesionario() throws SQLException {
        //Creo un nuevo objeto de tipo DefaultComboBoxModel y llamo al metodo
        DefaultComboBoxModel modeloConce = new DefaultComboBoxModel(this.conceDAO.mostrarConcesionarios());
        //añado el objeto al modeloConce
        comboConcesionario.setModel(modeloConce);
    }

    private void comboBoxMarca() throws SQLException {
        //Creo un nuevo objeto de tipo DefaultComboBoxModel y llamo al metodo
        DefaultComboBoxModel modeloMarca = new DefaultComboBoxModel(this.marcaDAO.mostrarMarcas());
        //añado el objeto al modeloMarca
        comboMarca.setModel(modeloMarca);
    }

    public void mostrarTablaMarcas(int pIdConcesionario) {

        //se crea un nuevo objeto de tipo DefaultTableModel
        DefaultTableModel modelo = new DefaultTableModel();

        //añado las columnas al modelo
        modelo.addColumn("IDMARCA");
        modelo.addColumn("MARCA");

        //Agrego el modelo a la tabla
        tablaConcesionarioMarca.setModel(modelo);

        String datos[] = new String[2];

        try {
            //Creo una nueva lista de tipo Marca
            List<Marca> lstMarca = conceDAO.listarMarcas(pIdConcesionario);

            //se recorre la lista para obtener los valores de la lista 
            lstMarca.forEach(m -> {

                //se obtienen los valores de la lista 
                datos[0] = String.valueOf(m.getIdMarca());
                datos[1] = m.getNombre();

                //se añaden los datos al modelo
                modelo.addRow(datos);
            });

        } catch (Exception e) {
            //muestro mensaje de error en caso de que no se ejecute correctamente            
            System.out.println("Error al obtener datos " + e.getMessage());
            //se muestra el mensaje de que a ocurrido un error al llenat la tabla
            JOptionPane.showMessageDialog(null, "Error en el llenado de la tabla");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        popEliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboConcesionario = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboMarca = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConcesionarioMarca = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        popEliminar.setText("Eliminar");
        popEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popEliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(popEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marcas Concesionario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Concesionario");

        comboConcesionario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboConcesionarioItemStateChanged(evt);
            }
        });
        comboConcesionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboConcesionarioMouseClicked(evt);
            }
        });
        comboConcesionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboConcesionarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Marcas en el Mercado");

        tablaConcesionarioMarca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaConcesionarioMarca.setComponentPopupMenu(jPopupMenu1);
        tablaConcesionarioMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablaConcesionarioMarcaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tablaConcesionarioMarca);

        jButton3.setText("Asignar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cerrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton3)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(comboConcesionario, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(comboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))))
                            .addGap(15, 15, 15))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboConcesionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        FrmConcesionario ventana = new FrmConcesionario();

        ventana.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void comboConcesionarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboConcesionarioItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            //alumno = (Alumno) comboalumnos.getSelectedItem();
            this.mostrarTablaMarcas(((Concesionario) comboConcesionario.getSelectedItem()).getIdConcesionario());
        }
    }//GEN-LAST:event_comboConcesionarioItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            //obtengo el item(ID) seleccionado del combo Concesionario
            this.conce = (Concesionario) comboConcesionario.getSelectedItem();
            //obtengo el item(ID) seleccionado del combo Marca
            this.marca = (Marca) comboMarca.getSelectedItem();

            int nMarca = conceDAO.getExisteMarcaConce(conce.getIdConcesionario(), marca.getIdMarca());

            if (nMarca < 1) {

                //llamo al metodo y obtengo los parametros
                conceDAO.agregarConcesionarioMarca(conce.getIdConcesionario(), marca.getIdMarca());
                //muestro la tabla para que se actualicen los datos
                mostrarTablaMarcas(((Concesionario) comboConcesionario.getSelectedItem()).getIdConcesionario());
                //muestro el mensaje de que se ejecuto correcto
                JOptionPane.showMessageDialog(null, "Datos guardados con exito!!!!");

            } else {
                
                JOptionPane.showMessageDialog(null, "Esta Marca ya está registrada en el Concesionario");

            }

        } catch (Exception e) {
            //muestro el mensaje en caso de que no se haya ejecutado correctamente 
            JOptionPane.showMessageDialog(null, "Error al agregar!!!");
            //se muestra el error en el output
            System.err.println("Error!!! " + e.getMessage());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboConcesionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboConcesionarioMouseClicked

    }//GEN-LAST:event_comboConcesionarioMouseClicked

    private void popEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popEliminarActionPerformed

        try {
            //obtengo el item seleccionado en el comboConcesionario y lo asigno a conce 
            this.conce = (Concesionario) comboConcesionario.getSelectedItem();
            //obtengo el item seleccionado en el comboMarca y lo asigno a marca
            this.marca = (Marca) comboMarca.getSelectedItem();
            //llamo al metodo y le paos los parametros
            conceDAO.eliminarMarcaConcesionario(conce.getIdConcesionario(), marca.getIdMarca());
            //muestro los datos de la tabla dependiendo del ID seleccionado del combo
            mostrarTablaMarcas(((Concesionario) comboConcesionario.getSelectedItem()).getIdConcesionario());
            //muestro el mensaje en caso de que se haya ejecutado correctamente
            JOptionPane.showMessageDialog(null, "Datos eliminados con exito!!!!");
        } catch (Exception e) {
            //muestro el mensaje en caso de que no se haya ejecutado correctamente
            JOptionPane.showMessageDialog(null, "Error al eliminar los datos!!!!");
            //Muestro el Error
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_popEliminarActionPerformed

    private void comboConcesionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboConcesionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboConcesionarioActionPerformed

    private void tablaConcesionarioMarcaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaConcesionarioMarcaMouseEntered

    }//GEN-LAST:event_tablaConcesionarioMarcaMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConcesionarioMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConcesionarioMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConcesionarioMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConcesionarioMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmConcesionarioMarca().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrmConcesionarioMarca.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboConcesionario;
    private javax.swing.JComboBox<String> comboMarca;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem popEliminar;
    private javax.swing.JTable tablaConcesionarioMarca;
    // End of variables declaration//GEN-END:variables
}
